import java.util.*;
import java.io.*;

public class Parser {

// =============================================================================
// The Main Method call for our RDBMS system. 
//   Essentially, this takes a input from Standard Input, removes empty or null
//   lines, and then passes this data to the Grammar to be parsed. 
// Parameters:
//   args: Needed Parameter for main method call, not used
// =============================================================================

	public static void main(String[] args) {

		// Take in from STDin
		ArrayList<String> input = new ArrayList<String>();
		Scanner file_input = new Scanner(System.in);

		// While the scanner reads in a new line...
		while (file_input.hasNextLine()) {
			String line = file_input.nextLine();

				// If it's not empty or null, and is valid, record it
			if (line != null && 
				!line.isEmpty() &&
				line.contains(";")) {
				input.add(line);
			}
		}

		// Pass each line to the Grammar to be parsed
		for (String line : input) {
			Grammar grammy = new Grammar();
			grammy.parseLine(line);
		}
	}

// =============================================================================
// A function to read in an input file generated by the Server
// =============================================================================

	public static String readMessage(String message) {
		// Split the incoming message by semicolons into separate lines
		ArrayList<String> input = new ArrayList<String>(Arrays.asList(message.split("\n")));

		// Pass each line to the Grammar to be parsed
		for (String line : input) {
			if (!line.isEmpty() && line.contains(";")) {
				Grammar grammy = new Grammar();
				return grammy.parseLine(line);
			}
		}
		return null;
	}
}